png("plot3.png", width = 480, height = 480)
plot(data_filtered$DateTime, data_filtered$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(data_filtered$DateTime, data_filtered$Sub_metering_2, col = "red")
lines(data_filtered$DateTime, data_filtered$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.off()
